version: "3.4"
services:
  react:
    image: react:app
    build:
      context: ./react
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - backend_app
    environment:
      - API_URL=http://localhost:8000 # This is how a browser would call the api
  api:
    image: api:app
    build:
      context: ./django
      dockerfile: Dockerfile
    command: gunicorn hello_django.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db # The api can address the db by its service name over the docker bridge network
      - DATABASE=postgres
    # depends_on:
    #   - db
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
networks:
  backend_app:
    driver: bridge
