version: "3.4"
services:
  react:
    image: react:app
    build:
      context: ./react
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    networks:
      - backend_app
    environment:
      - API_URL=http://api.dev.com
  api:
    image: api:app
    build:
      context: ./api
      dockerfile: ./Dockerfile
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
networks:
  backend_app:
    driver: bridge
