version: "3.4"
services:
  react:
    image: react:app
    build:
      context: ./react
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    networks:
      - backend_app
    environment:
      - API_URL=http://api.dev.com
networks:
  backend_app:
    driver: bridge
