openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing
paths:
  /section/0/{year}:
    get:
      summary: Returns section data for current year.
      description: Optional extended description in CommonMark or HTML.
      parameters: 
        - name: year
          in: path
          required: true
          description: Year of submission date
          schema:
            type : integer
            format: int64
            minimum: 4 
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                $ref: 'backend-json-section-0.json'  
  /section/1/{year}:
    get:
      summary: Returns section data for current year.
      description: Optional extended description in CommonMark or HTML.
      parameters: 
        - name: year
          in: path
          required: true
          description: Year of submission date
          schema:
            type : integer
            format: int64
            minimum: 4 
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                $ref: 'backend-json-section-1.json'
  /section/2/{year}:
    get:
      summary: Returns section data for current year.
      description: Optional extended description in CommonMark or HTML.
      parameters: 
        - name: year
          in: path
          required: true
          description: Year of submission date
          schema:
            type : integer
            format: int64
            minimum: 4 
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                $ref: 'backend-json-section-1.json'
  /section/3/{year}:
    get:
      summary: Returns section data for current year.
      description: Optional extended description in CommonMark or HTML.
      parameters: 
        - name: year
          in: path
          required: true
          description: Year of submission date
          schema:
            type : integer
            format: int64
            minimum: 4 
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                $ref: 'backend-json-section-1.json'
