name: schema validation

on:
  pull_request:
    paths:
      - 'docs/section-schemas/**.json'

jobs:
  schema_formatting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '14'
    - name: install prettier
      run: npm install prettier
    - name: run prettier against backend JSON
      run: ./.github/workflows/schema-format.sh
  schema_validation:
    runs-on: ubuntu-latest
    container: python:3.8
    steps:
      - uses: actions/checkout@v1
      - name: install dependencies
        run: pip install jsonschema jsonpath_ng
      - name: validate all documents
        run: ./.github/workflows/schema.sh
